FROM golang:1-alpine as builder

RUN apk --update --no-cache add musl-dev git gcc make ca-certificates

ARG TAG_NAME

WORKDIR /app

RUN git clone https://github.com/jaegertracing/jaeger.git . \
    && git checkout $TAG_NAME \
    && git submodule update --init --recursive \
    && make install-tools \
    && make build-agent -e GOOS=linux

FROM scratch

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

EXPOSE 5775/udp 6831/udp 6832/udp 5778

COPY --from=builder /app/cmd/agent/agent-linux /go/bin/

ENTRYPOINT ["/go/bin/agent-linux"]
